### ISSUE TITLE
Register form

### ISSUE THREAD

**Issue by Neiromaster** [getgrav/grav-plugin-login#113]
The submit button in the registration forms and the user profile does not work.
I use https://github.com/getgrav/grav-skeleton-rtfm-site for my site.
Don't work:
```php
    public function onFormProcessed(Event $event)
    {
        $form = $event['form'];
        $action = $event['action'];
        switch ($action) {
            case 'register_user':
                $this->processUserRegistration($form, $event);
                break;
            case 'update_user':
                $this->processUserProfile($form, $event);
                break;
        }
    }
```
from 
```yaml
process:
      register_user: true
      message: PLUGIN_LOGIN.LOGIN_SUCCESSFUL
```

**Comment by Vivalldi** [comment]
At first glance it would appear that you need to use only 2 spaces for your indentation in YAML.

```
process:
    register_user: true
    message: PLUGIN_LOGIN.LOGIN_SUCCESSFUL
```

If that does not change anything let me know and I'll take a look into it this evening.

**Comment by Neiromaster** [comment]
```yaml
  buttons:
    -
      type: submit
      value: PLUGIN_LOGIN.BTN_REGISTER
    -
      type: reset
      value: PLUGIN_LOGIN.BTN_CLEAR

  process:
    register_user: true
    message: PLUGIN_LOGIN.LOGIN_SUCCESSFUL
```

Problem still exists.
Execution does not reach the onFormProcessed method.
Only pages work in which `task` is registered
