### ISSUE TITLE
Form collision

### ISSUE THREAD

**Issue by bobrocke** [getgrav/grav-plugin-login#114]
I have added access control to a page that already has a form on it. The resulting collision of forms makes a predictable mess on the page.

Is there a way to keep the forms separate; the login form for the login page and the page's form once authentication is complete?

**Comment by rhukster** [comment]
How about redirecting to a login page that is not on the current page?

**Comment by bobrocke** [comment]
Hmmm. I see how to redirect from the login page after authentication. How do I redirect to login page itself?

**Comment by rhukster** [comment]
well you just set a route for the custom login location: https://github.com/getgrav/grav-plugin-login#login-page

**Comment by bobrocke** [comment]
I got that working, but... The login form at the custom login location can't seem to find the credentials file and doesn't recognize correct logins. Do I need to set the path to `user/accounts` somewhere?

**Comment by flaviocopes** [comment]
Admin and Site have a different session, so you can be logged in Admin with a user, and login to the frontend with another.

The credentials are automatically looked up in user/accounts, so just make sure the permissions are set up correctly as set in https://github.com/getgrav/grav-plugin-login#usage

**Comment by bobrocke** [comment]
OK, there can be separate logins - backend and frontend. Got it.

But the frontend login doesn't recognize the same credentials that the backend does. With the access I've set up:
```
access:
  site.login: true
  admin.login: true
```
that shouldn't be the case.

I must have something else missing. But what?

**Comment by flaviocopes** [comment]
It's definitely supposed  to work, and I just tested. 

If your user has one of those 2 access credentials, it will be logged in

**Comment by bobrocke** [comment]
Here are the credentials for the user:
```
email: bob@bobrockefeller.com
fullname: 'Bob Rockefeller'
title: 'Site Administrator'
access:
  admin:
    login: true
    super: true
authenticated: true
hashed_password: all-that-code
```
So it should be working. But it's not. :(

Can I Slack PM you my user folder?

**Comment by flaviocopes** [comment]
yes, PM me on Slack

**Comment by bobrocke** [comment]
@flaviocopes figured this one out. I needed to have `site.login` set for my user like this:
```
access:
  admin:
    login: true
    super: true
  site:
    login: true
```
