### ISSUE TITLE
Missing User and password input fields in a page with login form

### ISSUE THREAD

**Issue by Sergiop79** [getgrav/grav-plugin-login#200]
Hi

I have a problem creating a page with a login form.

I'm creating a custom theme.

Plugins used:

- login v2.8.3, config yaml https://gist.github.com/Sergiop79/b47035460118b2b5676c5b9430ff5ba3
- Admin Panel  v1.8.16
- Maintenance  v1.3.2

GRAV v1.5.7

The problem is that the user and password fields are missing when I include the login form, this is the template code:

```html
{% extends 'partials/base.html.twig' %}

{% block content %}

    <div id="maintenance-login" style="text-align: center;">
        {% include 'partials/login-form.html.twig' with {content: 'PLUGIN_MAINTENANCE.AUTHORIZED_ACCESS'|t|markdown,
        show_login_form: true }%}
    </div>
{% endblock %}
```

An this is the result:

![captura de pantalla de 2019-02-06 11-30-32](https://user-images.githubusercontent.com/3718414/52335418-ab139800-2a02-11e9-90e7-061b63309602.png)

The same problem is replicated when using Maintenance mode activated and enabled the login form:

![captura de pantalla de 2019-02-06 11-34-22](https://user-images.githubusercontent.com/3718414/52335648-31c87500-2a03-11e9-85ab-cf611b5a93af.png)

What can I do to solve this?

Thanks

**Comment by rhukster** [comment]
You also need the `form` plugin.

**Comment by Sergiop79** [comment]
Hi @rhukster 

Thanks for the answer.

I have the form plugin installed to. These are the plugins I have installed now:

![captura de pantalla de 2019-02-13 09-10-49](https://user-images.githubusercontent.com/3718414/52696621-b8cf9d00-2f6f-11e9-8978-4699174bd0f0.png)

The Grav version now is v1.5.8 

But the user and input fields are missing when activating the maintenance mode.

Thanks

**Comment by rhukster** [comment]
Are you running version 1.3.2 of the maintenance plugin?

Your Twig 'should' look like this by default:

```
{% extends 'partials/base.html.twig' %}

{% block content %}

    {{ page.content|default('PLUGIN_MAINTENANCE.OFFLINE_MARKDOWN'|t|markdown|raw) }}

    {% if maintenance.allow_login and not grav.user.authenticated %}
        <div id="maintenance-login" style="text-align: center;">
            {% include 'partials/login-form.html.twig' with {content: 'PLUGIN_MAINTENANCE.AUTHORIZED_ACCESS'|t|markdown, show_login_form: true }%}
        </div>
    {% endif %}
{% endblock %}
```

**Comment by Sergiop79** [comment]
I have maintenance 1.3.2 and with the default template the result is the same. User and password fields are missing:

![captura de pantalla de 2019-02-14 10-58-12](https://user-images.githubusercontent.com/3718414/52779276-13d4c300-3048-11e9-8c2c-02bc61908e8f.png)


Al I want is that any admin could see the frontend of the site at the same time with the maintenance mode activated.

**Comment by mahagr** [comment]
Try adding `user/pages/login/login.md` with this content:

```
---
title: Login
login_redirect_here: false
classes: login-backdrop

forms:
  login:
    client_side_validation: true

    fields:
      username:
        type: text
        id: username
        label: Email Address
        autofocus: true
        datasets:
          value-missing: 'email field required'
        validate:
          required: true
          
      password:
        type: password
        id: password
        label: Password
        datasets:
          value-missing: 'password field required'
        validate:
            required: true
---

# Login

```
