### ISSUE TITLE
On save in /admin/user/theuser the YAML content access part is deleted for further users

### ISSUE THREAD

**Issue by cyberlussi** [getgrav/grav-plugin-login#203]
Hi,

I created according to learn.grav a new user on cmdline. As I like to have limited access for this user, I edited the yaml file and added 
```
access:
  admin:
    login: 'true'
    pages: 'true'
    statistics: 'true'
  site:
    login: 'true'
```
This works fine for login and limited view in the admin plugin. But when opening /admin/user/theuser and just doing "Save", the yaml is cleaned too much. The complete "access" block is gone. The user cannot login any more. 

Nevertheless, for the initially created admin user it seems to work on save. I am using v3.0.0-rc.3.
