### ISSUE TITLE
Group-based permissions are not working.

### ISSUE THREAD

**Issue by jefersonbc** [getgrav/grav-plugin-login#40]
Hi,

groups defined in 'user/config/groups.yaml' are not working.

**user/config/groups.yaml :**
```
premium:
  readableName: 'Premium Members'
  description: 'The group of premium members'
  access:
    admin:
      login: true
      super: true
    site:
      login: true
      paid: true
```

**user/accounts/user.yaml**
```
...
groups:
  - premium
```

I missed something?

References: http://learn.getgrav.org/cookbook/general-recipes#use-group-based-permissions

**Comment by flaviocopes** [comment]
Can you explain not working? What problem did you stumble upon and what was instead the expected result? How to replicate?

**Comment by jefersonbc** [comment]
When groups are defined, the users must inherit the group permissions, but this is not happens.

I set a group 'premium'  in **groups.yaml**, with the permissions:
```
admin:
  login: true
  super: true
site:
  login: true
  paid: true
```

and this group was assigned to my user (**user.yaml**)
```
groups:
  - premium
```

I removed the user permissions and set the group 'premium', but group permissions were not inherited by the user.

For example, I receive the message 'Access denied...' when I try to access the admin area. This should not be happening, since the user is in group 'Premium', and this group has the permission to access the admin area.

To replicate, create a group. Then, remove user access permissions and set the group for the user. After this, try to access the admin area.
