### ISSUE TITLE
Oauth creates users with faulty user rights

### ISSUE THREAD

**Issue by Ricoom** [getgrav/grav-plugin-login#54]
Correct working user rights on user.yaml are 
access:
`access:`
`    site:`
`       login: true`

what oauth generates

`access:`
`    site.login: '1'`

problem is not weather there is true or '1' but in the formatting which leads to setting rights manually.
@flaviocopes

**Comment by flaviocopes** [comment]
```
access:
  site.login: '1'
```

and 

```
access:
  site:
    login: true
```

are equivalent.

I just tested, things seem to be fine. After creating the user, the user is logged in.

Please indent properly as from what you write I can't determine if the spacing is correct. Use triple backticks.

**Comment by flaviocopes** [comment]
Double-checked. Legitimate issue. Was trying some changes but the user access was cached so I could not reproduce it.

**Comment by Ricoom** [comment]
page header
```
title: secure
slug: secure
access:
    site.right: true
```
plugin settings 
[http://imgur.com/dO9veE8](url)

Oauth auto generated user

```
email: some@email.com
lang: ''
access:
  site.login: '1'
  site.right: '1'
authenticated: false
hashed_password: $SOMECOOLHASH
```

command line generated user

```
email: some@email.com
access:
  admin:
    login: true
    super: true
  site:
    login: true
fullname: 'Full Name'
title: Developer
state: enabled
hashed_password: $SOMECOOLHASH
```
if I add the permission 'right' to the command line generated file in that format it works 

```
email: some@email.com
access:
  admin:
    login: true
    super: true
  site:
    login: true
    right: true
fullname: 'Full Name'
title: Developer
state: enabled
hashed_password: $SOMECOOLHASH
```

Oauth generated version does not work
