### ISSUE TITLE
Username already exists

### ISSUE THREAD

**Issue by butchewing** [getgrav/grav-plugin-login#92]
With my custom registration form, I keep getting `Username already exists, please pick another username` even though there is currently only one user with a different username.

**Comment by flaviocopes** [comment]
What's your custom registration form content?

**Comment by butchewing** [comment]
```
forms:
    register-form:
        fields:
            -
                name: fullname
                label: 'Name'
                type: text
                validate: { required: true }
            -
                name: company
                label: Company
                type: text
                validate: { required: true }
            -
                name: position
                label: Position
                type: text
                validate: { required: true }
            -
                name: Email
                type: email
                validate: { required: true, message: PLUGIN_LOGIN.EMAIL_VALIDATION_MESSAGE }
            -
                name: Username
                type: text
                validate: { required: true, message: PLUGIN_LOGIN.USERNAME_NOT_VALID, pattern: '^[a-z0-9_-]{3,16}$' }
            -
                name: password1
                type: password
                label: 'Enter a password'
                validate: { required: true, message: PLUGIN_LOGIN.PASSWORD_VALIDATION_MESSAGE, pattern: '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}' }
            -
                name: password2
                type: password
                label: 'Repeat the password'
                validate: { required: true, message: PLUGIN_LOGIN.PASSWORD_VALIDATION_MESSAGE, pattern: '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}' }
        buttons:
            -
                type: submit
                value: Submit
            -
                type: reset
                value: Reset
        process:
            register_user: true
            display: /resources/dashboard
            message: Welcome!
```
