### ISSUE TITLE
ACL Access denied...

### ISSUE THREAD

**Issue by butchewing** [getgrav/grav-plugin-login#94]
Registration and Login are working great. But, I login and try to access a private page, I get Access denied. How can I debug this?

**config/plugins/login.yaml**

```
parent_acl: true
protect_protected_page_media: true
user_registration:
  enabled: true
  fields:
    - firstname
    - lastname
    - company
    - 'job title'
    - email
    - username
    - password
  access:
    site:
      login: 'true'
```

**accounts/user.yaml**

```
access:
  site:
    login: 'true'
```

**default.md**

```
access:
  site:
    login: true
```
